'use client'
import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import ReactMarkdown from 'react-markdown'
import { supabase } from '@/lib/supabase'

interface BlogPostData {
  id?: string
  title: string
  slug: string
  summary: string
  body_md: string
  tags: string
  seo_title: string
  seo_description: string
  source_urls: string
  status: 'draft' | 'published'
  created_by?: string
}

interface Props {
  initialData?: BlogPostData & { id: string }
}

function slugify(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 60)
}

export default function BlogEditor({ initialData }: Props) {
  const router = useRouter()
  const [saving, setSaving] = useState(false)
  const [preview, setPreview] = useState(false)

  const [form, setForm] = useState<BlogPostData>({
    title: initialData?.title ?? '',
    slug: initialData?.slug ?? '',
    summary: initialData?.summary ?? '',
    body_md: initialData?.body_md ?? '',
    tags: initialData?.tags ?? '',
    seo_title: initialData?.seo_title ?? '',
    seo_description: initialData?.seo_description ?? '',
    source_urls: initialData?.source_urls ?? '',
    status: initialData?.status ?? 'draft',
    created_by: initialData?.created_by,
  })

  // Auto-generate slug from title (only if slug is empty or was auto-generated)
  const [slugManual, setSlugManual] = useState(!!initialData?.slug)
  useEffect(() => {
    if (!slugManual && form.title) {
      setForm(f => ({ ...f, slug: slugify(f.title) }))
    }
  }, [form.title, slugManual])

  const set = (field: keyof BlogPostData) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) =>
    setForm(f => ({ ...f, [field]: e.target.value }))

  const save = async (publish: boolean) => {
    if (!form.title || !form.slug || !form.summary || !form.body_md) {
      alert('Title, slug, summary, and body are required.')
      return
    }
    setSaving(true)
    const payload: Record<string, unknown> = {
      title: form.title,
      slug: form.slug,
      summary: form.summary,
      body_md: form.body_md,
      tags: form.tags.split(',').map(t => t.trim()).filter(Boolean),
      seo_title: form.seo_title || null,
      seo_description: form.seo_description || null,
      source_urls: form.source_urls.split('\n').map(u => u.trim()).filter(Boolean),
      status: publish ? 'published' : 'draft',
    }
    if (publish && form.status !== 'published') {
      payload.published_at = new Date().toISOString()
    }

    if (initialData?.id) {
      await supabase.from('blog_posts').update(payload).eq('id', initialData.id)
    } else {
      await supabase.from('blog_posts').insert(payload)
    }
    setSaving(false)
    router.push('/admin/blog')
    router.refresh()
  }

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <div className="flex items-center gap-3 mb-6">
        <button onClick={() => router.push('/admin/blog')} className="text-sm text-blue-600 hover:text-blue-700">← Back to Blog</button>
        <h1 className="text-2xl font-bold text-gray-900">{initialData ? 'Edit Post' : 'New Post'}</h1>
        {form.created_by === 'claw' && (
          <span className="inline-flex items-center text-xs text-purple-600 bg-purple-50 px-2 py-0.5 rounded-full">🦞 Generated by Claw</span>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Form */}
        <div className="space-y-4">
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">Title *</label>
            <input
              value={form.title}
              onChange={set('title')}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Clear, SEO-friendly title"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">Slug *</label>
            <input
              value={form.slug}
              onChange={e => { setSlugManual(true); set('slug')(e) }}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="url-slug-here"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">Summary * (used as meta description)</label>
            <textarea
              value={form.summary}
              onChange={set('summary')}
              rows={2}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
              placeholder="1-2 sentence summary..."
            />
          </div>
          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="block text-xs font-medium text-gray-700">Body (Markdown) *</label>
              <button
                onClick={() => setPreview(p => !p)}
                className="text-xs text-blue-600 hover:text-blue-700"
              >
                {preview ? 'Edit' : 'Preview'}
              </button>
            </div>
            <textarea
              value={form.body_md}
              onChange={set('body_md')}
              rows={16}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500 resize-y"
              placeholder="Write your post in markdown..."
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">Tags (comma-separated)</label>
            <input
              value={form.tags}
              onChange={set('tags')}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="ai-patents, uspto, patent-filing"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">SEO Title (optional, max 60 chars)</label>
            <input
              value={form.seo_title}
              onChange={set('seo_title')}
              maxLength={60}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Override title for search engines"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">SEO Description (optional, max 155 chars)</label>
            <textarea
              value={form.seo_description}
              onChange={set('seo_description')}
              maxLength={155}
              rows={2}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
              placeholder="Override meta description"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">Source URLs (one per line)</label>
            <textarea
              value={form.source_urls}
              onChange={set('source_urls')}
              rows={3}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
              placeholder="https://example.com/article"
            />
          </div>

          <div className="flex gap-3 pt-2">
            <button
              onClick={() => save(false)}
              disabled={saving}
              className="flex-1 px-4 py-2.5 border border-gray-300 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50"
            >
              {saving ? 'Saving...' : 'Save Draft'}
            </button>
            <button
              onClick={() => save(true)}
              disabled={saving}
              className="flex-1 px-4 py-2.5 bg-blue-600 text-white text-sm font-semibold rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50"
            >
              {saving ? 'Publishing...' : 'Publish'}
            </button>
          </div>
        </div>

        {/* Right: Preview */}
        <div className="hidden lg:block">
          <div className="sticky top-6">
            <div className="text-xs font-medium text-gray-500 mb-2 uppercase tracking-wide">Preview</div>
            <div className="bg-white rounded-xl border border-gray-200 p-6 max-h-[80vh] overflow-y-auto">
              {form.title && <h1 className="text-2xl font-bold text-gray-900 mb-3">{form.title}</h1>}
              {form.summary && <p className="text-gray-500 text-sm mb-4 italic">{form.summary}</p>}
              <div className="prose prose-sm prose-gray max-w-none">
                <ReactMarkdown>{form.body_md || '*Start typing to see preview...*'}</ReactMarkdown>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Mobile preview toggle */}
      {preview && (
        <div className="lg:hidden mt-6 bg-white rounded-xl border border-gray-200 p-6">
          <div className="prose prose-sm prose-gray max-w-none">
            <ReactMarkdown>{form.body_md}</ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  )
}
