'use client'
import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import Link from 'next/link'
import { supabase, Patent } from '@/lib/supabase'

interface IntakeSession {
  inventor_name: string | null
  inventor_email: string | null
  co_inventors: string[]
  micro_entity_eligible: boolean | null
}

function Field({ label, value, note }: { label: string; value?: string | null; note?: string }) {
  return (
    <div className="mb-4">
      <div className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-1">{label}</div>
      <div className={`text-sm border-b pb-1 ${value ? 'border-gray-400 text-gray-900' : 'border-gray-300 text-gray-300'}`}>
        {value || '___________________________________'}
      </div>
      {note && <div className="text-xs text-gray-400 mt-0.5 italic">{note}</div>}
    </div>
  )
}

export default function CoverSheetPage() {
  const params = useParams()
  const router = useRouter()
  const patentId = params.id as string
  const [patent, setPatent] = useState<Patent | null>(null)
  const [intake, setIntake] = useState<IntakeSession | null>(null)
  const [loading, setLoading] = useState(true)
  const [today] = useState(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }))

  useEffect(() => {
    async function load() {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) { router.push('/login'); return }

      const { data: p } = await supabase.from('patents').select('*').eq('id', patentId).single()
      if (!p) { router.push('/dashboard/patents'); return }
      setPatent(p)

      if (p.intake_session_id) {
        const { data: s } = await supabase
          .from('patent_intake_sessions')
          .select('inventor_name, inventor_email, co_inventors, micro_entity_eligible')
          .eq('id', p.intake_session_id)
          .single()
        if (s) setIntake(s as IntakeSession)
      }
      setLoading(false)
    }
    load()
  }, [patentId, router])

  if (loading) return <div className="flex items-center justify-center h-screen text-gray-400">Loading…</div>
  if (!patent) return null

  const inventors = [
    intake?.inventor_name || patent.inventors?.[0] || null,
    ...(intake?.co_inventors || patent.inventors?.slice(1) || []),
  ].filter(Boolean) as string[]

  const entityStatus = intake?.micro_entity_eligible === true ? 'Micro Entity' :
    intake?.micro_entity_eligible === false ? 'Small Entity' : 'Small Entity (unconfirmed)'

  const today2 = new Date().toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' })

  return (
    <div className="min-h-screen bg-white" style={{ fontFamily: 'Georgia, "Times New Roman", serif' }}>
      {/* Toolbar (non-printable) */}
      <div className="print:hidden bg-[#1a1f36] text-white px-6 py-3 flex items-center justify-between gap-4 sticky top-0 z-10">
        <Link href={`/dashboard/patents/${patentId}`} className="text-sm text-gray-300 hover:text-white">
          ← Back to Patent
        </Link>
        <span className="text-sm font-semibold">USPTO Form SB/16 — Pre-filled Cover Sheet</span>
        <div className="flex items-center gap-3">
          <button
            onClick={() => window.print()}
            className="px-4 py-1.5 bg-white text-[#1a1f36] rounded text-sm font-bold hover:bg-gray-100"
          >
            🖨️ Print / Save PDF
          </button>
          <Link
            href={`/dashboard/patents/${patentId}?ack=cover-sheet`}
            className="px-4 py-1.5 bg-green-500 text-white rounded text-sm font-bold hover:bg-green-600"
          >
            ✅ Mark as Complete
          </Link>
        </div>
      </div>

      {/* Cover sheet content */}
      <div className="max-w-3xl mx-auto px-8 py-10">
        {/* Header */}
        <div className="text-center mb-8 pb-6 border-b-2 border-gray-800">
          <div className="text-xs font-sans text-gray-500 mb-2">
            UNITED STATES PATENT AND TRADEMARK OFFICE
          </div>
          <h1 className="text-xl font-bold mb-1">
            APPLICATION FOR PATENT — PROVISIONAL
          </h1>
          <div className="text-sm text-gray-600">
            COVER SHEET — Based on Form PTO/SB/16
          </div>
          <div className="text-xs text-gray-400 mt-2 font-sans">
            Generated by PatentPending.app · {today} · Pre-filled from your intake data
          </div>
          <div className="mt-3 p-3 bg-amber-50 border border-amber-300 rounded text-xs font-sans text-amber-800">
            ⚠️ DRAFT — Review all fields before submission. Blank fields must be completed manually.
            File this with USPTO Patent Center at <strong>patentcenter.uspto.gov</strong>
          </div>
        </div>

        {/* Section 1: Invention */}
        <section className="mb-8">
          <h2 className="text-sm font-bold border-b border-gray-400 pb-1 mb-4 uppercase tracking-wider">
            1. Invention Information
          </h2>
          <Field
            label="Title of Invention"
            value={patent.title}
            note="5–10 words describing the invention"
          />
          <div className="grid grid-cols-2 gap-6">
            <Field label="Application Number" value="" note="Leave blank — assigned upon filing" />
            <Field label="Filing Date" value="" note="Assigned by USPTO upon receipt" />
          </div>
          <div className="grid grid-cols-2 gap-6">
            <Field label="Confirmation Number" value="" note="Assigned upon filing" />
            <Field label="Art Unit" value="" note="Assigned by USPTO" />
          </div>
        </section>

        {/* Section 2: Inventors */}
        <section className="mb-8">
          <h2 className="text-sm font-bold border-b border-gray-400 pb-1 mb-4 uppercase tracking-wider">
            2. Inventor(s)
          </h2>
          {inventors.length > 0 ? inventors.map((inv, i) => (
            <div key={i} className="mb-5 pl-3 border-l-2 border-gray-300">
              <div className="text-xs font-bold text-gray-500 mb-2 uppercase">
                Inventor {i + 1}{i === 0 ? ' (First Named)' : ''}
              </div>
              <div className="grid grid-cols-3 gap-4">
                <Field label="Family Name" value={inv.split(' ').slice(-1)[0] || ''} />
                <Field label="Given Name" value={inv.split(' ').slice(0, -1).join(' ') || ''} />
                <Field label="Middle Name / Initial" value="" />
              </div>
              <div className="grid grid-cols-3 gap-4">
                <Field label="City of Residence" value="" note="Required by USPTO" />
                <Field label="State / Province" value="" />
                <Field label="Country" value="US" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <Field label="Citizenship" value="United States" />
                <Field label="Email" value={i === 0 ? (intake?.inventor_email || '') : ''} />
              </div>
            </div>
          )) : (
            <div className="pl-3 border-l-2 border-amber-300 text-sm text-amber-700">
              ⚠️ No inventor information found. Add inventor details via the patent detail page.
            </div>
          )}
        </section>

        {/* Section 3: Correspondence */}
        <section className="mb-8">
          <h2 className="text-sm font-bold border-b border-gray-400 pb-1 mb-4 uppercase tracking-wider">
            3. Correspondence Address
          </h2>
          <div className="text-xs font-sans text-gray-500 mb-3">
            Check one: □ Customer Number &nbsp;&nbsp; ■ Correspondence Address Below
          </div>
          <div className="grid grid-cols-2 gap-4">
            <Field label="Name" value={inventors[0] || ''} />
            <Field label="Firm Name (if applicable)" value="" />
          </div>
          <Field label="Address Line 1" value="" note="Street address" />
          <Field label="Address Line 2" value="" note="City, State, ZIP" />
          <div className="grid grid-cols-2 gap-4">
            <Field label="Country" value="US" />
            <Field label="Telephone" value="" />
          </div>
          <Field label="Email" value={intake?.inventor_email || ''} />
        </section>

        {/* Section 4: Entity Status */}
        <section className="mb-8">
          <h2 className="text-sm font-bold border-b border-gray-400 pb-1 mb-4 uppercase tracking-wider">
            4. Entity Status
          </h2>
          <div className="text-sm">
            <div className="flex items-center gap-3 mb-2">
              <span className="font-bold">{intake?.micro_entity_eligible === true ? '■' : '□'}</span>
              <span>Micro Entity — See 37 CFR 1.29. USPTO fees reduced by ~80%.</span>
            </div>
            <div className="flex items-center gap-3 mb-2">
              <span className="font-bold">{intake?.micro_entity_eligible === false ? '■' : '□'}</span>
              <span>Small Entity — See 37 CFR 1.27. USPTO fees reduced by ~60%.</span>
            </div>
            <div className="flex items-center gap-3">
              <span className="font-bold">□</span>
              <span>Undiscounted (Large Entity)</span>
            </div>
            <div className="mt-2 text-xs font-sans text-gray-500">
              Detected from intake data: <strong>{entityStatus}</strong>
            </div>
          </div>
        </section>

        {/* Section 5: Prior Applications */}
        <section className="mb-8">
          <h2 className="text-sm font-bold border-b border-gray-400 pb-1 mb-4 uppercase tracking-wider">
            5. Prior Related Applications (if any)
          </h2>
          <div className="grid grid-cols-3 gap-4">
            <Field label="Prior App. Number" value={patent.provisional_number || ''} />
            <Field label="Filing Date" value="" />
            <Field label="Relation" value="Provisional" />
          </div>
          <div className="text-xs font-sans text-gray-500 mt-2">
            If this is the provisional itself, leave blank. If filing a non-provisional, reference the provisional number above.
          </div>
        </section>

        {/* Section 6: Signature */}
        <section className="mb-8">
          <h2 className="text-sm font-bold border-b border-gray-400 pb-1 mb-4 uppercase tracking-wider">
            6. Signature
          </h2>
          <div className="grid grid-cols-2 gap-6">
            <Field label="Signature of Applicant / Attorney" value="" note="Required — sign in Patent Center" />
            <Field label="Date" value={today2} />
          </div>
          <Field label="Typed or Printed Name" value={inventors[0] || ''} />
          <Field label="Registration Number (if applicable)" value="" note="Leave blank if filing pro se" />
        </section>

        {/* Footer */}
        <div className="border-t border-gray-300 pt-4 text-xs font-sans text-gray-400 text-center">
          <p>Generated by PatentPending.app on {today}. This is a pre-populated guide — not a substitute for the official USPTO form.</p>
          <p className="mt-1">File provisionals at: <strong>patentcenter.uspto.gov</strong> · Use form PTO/SB/16 · Allow 1–3 business days for confirmation.</p>
          <p className="mt-1 text-amber-600">PatentPending.app is not a law firm. This is not legal advice.</p>
        </div>
      </div>

      {/* Print styles */}
      <style>{`
        @media print {
          .print\\:hidden { display: none !important; }
          body { font-size: 12pt; }
          @page { margin: 0.75in; }
        }
      `}</style>
    </div>
  )
}
