import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

/**
 * USPTO Patent Center requires PDF version 1.1–1.6.
 * pdf-lib generates PDF 1.7 — patch the header before returning.
 */
async function fixPdfVersion(pdfBytes: Uint8Array): Promise<Uint8Array> {
  const buf = Buffer.from(pdfBytes)
  const header = buf.toString('ascii', 0, 8)
  if (header.includes('PDF-1.7')) {
    buf.write('%PDF-1.6', 0, 'ascii')
  }
  return new Uint8Array(buf)
}

export interface SigningRequestData {
  document_type: string
  document_label: string
  signer_name: string
  s_signature: string
  signed_date: string
  prefill_data: {
    application_number?: string
    filing_date?: string
    patent_title?: string
  }
}

const PAGE_WIDTH = 612
const PAGE_HEIGHT = 792
const MARGIN = 72
const BODY_SIZE = 10
const HEADER_SIZE = 12
const LINE_HEIGHT = 16
const FOOTER = 'Generated by PatentPending.app | patentpending.app'

async function createBase(title: string): Promise<{
  doc: PDFDocument
  page: ReturnType<PDFDocument['addPage']>
  helveticaBold: Awaited<ReturnType<PDFDocument['embedFont']>>
  helvetica: Awaited<ReturnType<PDFDocument['embedFont']>>
  y: { val: number }
  drawText: (text: string, opts?: { bold?: boolean; size?: number; indent?: number }) => void
  drawBlankLine: () => void
}> {
  const doc = await PDFDocument.create()
  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
  const helvetica = await doc.embedFont(StandardFonts.Helvetica)
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold)

  const y = { val: PAGE_HEIGHT - MARGIN }

  function drawText(
    text: string,
    opts: { bold?: boolean; size?: number; indent?: number } = {}
  ) {
    const font = opts.bold ? helveticaBold : helvetica
    const size = opts.size ?? BODY_SIZE
    const x = MARGIN + (opts.indent ?? 0)
    const maxWidth = PAGE_WIDTH - 2 * MARGIN - (opts.indent ?? 0)

    // Word-wrap
    const words = text.split(' ')
    let line = ''
    for (const word of words) {
      const test = line ? `${line} ${word}` : word
      const testWidth = font.widthOfTextAtSize(test, size)
      if (testWidth > maxWidth && line) {
        page.drawText(line, { x, y: y.val, font, size, color: rgb(0, 0, 0) })
        y.val -= LINE_HEIGHT
        line = word
      } else {
        line = test
      }
    }
    if (line) {
      page.drawText(line, { x, y: y.val, font, size, color: rgb(0, 0, 0) })
      y.val -= LINE_HEIGHT
    }
  }

  function drawBlankLine() {
    y.val -= LINE_HEIGHT
  }

  // Draw title at top
  drawText(title, { bold: true, size: HEADER_SIZE })
  drawBlankLine()

  // Footer
  const footerFont = helvetica
  const footerSize = 8
  const footerWidth = footerFont.widthOfTextAtSize(FOOTER, footerSize)
  page.drawText(FOOTER, {
    x: (PAGE_WIDTH - footerWidth) / 2,
    y: MARGIN / 2,
    font: footerFont,
    size: footerSize,
    color: rgb(0.5, 0.5, 0.5),
  })

  return { doc, page, helvetica, helveticaBold, y, drawText, drawBlankLine }
}

export async function generateSignedPdf(
  request: SigningRequestData,
  patentTitle: string
): Promise<Uint8Array> {
  const appNum = request.prefill_data.application_number ?? 'To Be Assigned'
  const filingDate = request.prefill_data.filing_date ?? ''

  if (request.document_type === 'aia_01') {
    const { doc, drawText, drawBlankLine } = await createBase(
      'DECLARATION FOR UTILITY OR DESIGN PATENT APPLICATION'
    )
    drawText('(37 CFR 1.63; 1.64)', { bold: false })
    drawText('PTO/AIA/01')
    drawBlankLine()
    drawText(`Application Number: ${appNum}`)
    drawText(`Filing Date: ${filingDate}`)
    drawText(`Title of Invention: ${patentTitle}`)
    drawBlankLine()
    drawText('I hereby declare that:', { bold: true })
    drawBlankLine()
    drawText(
      '(1) I am an original inventor, or an original joint inventor, of a claimed invention in the application identified above;',
      { indent: 16 }
    )
    drawBlankLine()
    drawText('(2) this application was made or authorized to be made by me; and', { indent: 16 })
    drawBlankLine()
    drawText(
      `(3) I believe I am the original inventor or an original joint inventor of any subject matter which is claimed and for which a patent is sought on the invention titled: ${patentTitle}`,
      { indent: 16 }
    )
    drawBlankLine()
    drawBlankLine()
    drawText(
      'WARNING: Petitioner/applicant is cautioned to avoid submitting personal information in documents filed in a patent application that may contribute to identity theft.',
      { bold: true }
    )
    drawBlankLine()
    drawBlankLine()
    drawText(`Signature: ${request.s_signature}`)
    drawText(`Printed Name: ${request.signer_name}`)
    drawText(`Date: ${request.signed_date}`)

    return await fixPdfVersion(await doc.save())
  }

  if (request.document_type === 'sb0015a') {
    const { doc, drawText, drawBlankLine } = await createBase(
      'CERTIFICATION OF MICRO ENTITY STATUS'
    )
    drawText('(37 CFR 1.29)')
    drawText('Form SB/0015a')
    drawBlankLine()
    drawText(`Application Number: ${appNum}`)
    drawText(`Title of Invention: ${patentTitle}`)
    drawBlankLine()
    drawText(
      'The undersigned hereby certifies that they qualify as a micro entity as defined in 37 CFR 1.29:',
      { bold: true }
    )
    drawBlankLine()
    drawText('(1) I qualify as a small entity;', { indent: 16 })
    drawBlankLine()
    drawText(
      '(2) I have not been named as an inventor on more than 4 previously filed patent applications;',
      { indent: 16 }
    )
    drawBlankLine()
    drawText(
      '(3) My gross income in the preceding calendar year did not exceed the micro entity income limit ($271,900 for calendar year 2025) and I have not assigned, granted, or conveyed — and am not obligated to assign, grant, or convey — a license or ownership interest in this application to an entity that had a gross income exceeding the micro entity income limit.',
      { indent: 16 }
    )
    drawBlankLine()
    drawBlankLine()
    drawText(
      'WARNING: Petitioner/applicant is cautioned to avoid submitting personal information in documents filed in a patent application that may contribute to identity theft.',
      { bold: true }
    )
    drawBlankLine()
    drawBlankLine()
    drawText(`Signature: ${request.s_signature}`)
    drawText(`Printed Name: ${request.signer_name}`)
    drawText(`Date: ${request.signed_date}`)

    return await fixPdfVersion(await doc.save())
  }

  // Generic: assignment, aia_08, other
  const { doc, drawText, drawBlankLine } = await createBase('SIGNED DOCUMENT COVER PAGE')
  drawBlankLine()
  drawText(`Document: ${request.document_label}`)
  drawText(`Patent Application: ${patentTitle}`)
  drawText(`Application Number: ${appNum}`)
  drawBlankLine()
  drawBlankLine()
  drawText(
    'This document has been signed electronically pursuant to 37 CFR 1.4(d)(2).',
    { bold: true }
  )
  drawBlankLine()
  drawBlankLine()
  drawText(`Signature: ${request.s_signature}`)
  drawText(`Printed Name: ${request.signer_name}`)
  drawText(`Date: ${request.signed_date}`)

  return await fixPdfVersion(await doc.save())
}
